"""empty message

Revision ID: b662965ba0fd
Revises: 47c5a723da23
Create Date: 2022-01-03 08:56:32.128961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b662965ba0fd'
down_revision = '47c5a723da23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
