"""empty message

Revision ID: dff1f0b047be
Revises: f064e47b60fa
Create Date: 2022-01-03 09:14:31.097623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dff1f0b047be'
down_revision = 'f064e47b60fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'owner_email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'owner_email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
