"""empty message

Revision ID: f064e47b60fa
Revises: b662965ba0fd
Create Date: 2022-01-03 09:11:21.831355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f064e47b60fa'
down_revision = 'b662965ba0fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('owner_email', sa.String(), nullable=False))
    op.create_foreign_key(None, 'posts', 'users', ['owner_email'], ['email'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_column('posts', 'owner_email')
    # ### end Alembic commands ###
